"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowDownLeft, ArrowUpRight, BarChart3, CalendarDays, ChevronLeft, TrendingDown, TrendingUp } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ReportChart } from "@/features/reports/components/report-chart";
import type { ReportData, ReportRange } from "@/features/reports/queries/get-report";
import { formatCurrency } from "@/lib/utils";

const rangeLabels: Record<ReportRange, string> = { week: "Tuần này", month: "Tháng này", year: "Năm nay", custom: "Tùy chỉnh" };
const fallback: ReportData = { range: "month", from: "2026-09-01", to: "2026-09-30", periodLabel: "Tháng 9/2026", trendLabel: "6 tháng gần nhất", income: 18_000_000, expense: 3_320_000, net: 14_680_000, savingRate: 81.6, transactionCount: 12, topCategories: [{ id: "food", name: "Ăn uống", color: "#087f5b", amount: 2_180_000, percentage: 65.7 }, { id: "move", name: "Di chuyển", color: "#efaa47", amount: 820_000, percentage: 24.7 }, { id: "shopping", name: "Mua sắm", color: "#8795c4", amount: 320_000, percentage: 9.6 }], trend: [{ label: "04/2026", income: 14_000_000, expense: 4_500_000, net: 9_500_000 }, { label: "05/2026", income: 16_000_000, expense: 5_100_000, net: 10_900_000 }, { label: "06/2026", income: 17_000_000, expense: 4_200_000, net: 12_800_000 }, { label: "07/2026", income: 18_000_000, expense: 3_800_000, net: 14_200_000 }, { label: "08/2026", income: 18_000_000, expense: 3_600_000, net: 14_400_000 }, { label: "09/2026", income: 18_000_000, expense: 3_320_000, net: 14_680_000 }] };

export function ReportsView({ data, configured }: { data: ReportData | null; configured: boolean }) {
  const router = useRouter();
  const report = data ?? fallback;
  function changeRange(value: string) { router.push(`/app/reports?range=${value}`); }
  return <main className="min-h-screen bg-[var(--background)] px-4 pb-28 pt-5 sm:px-6 md:px-10 md:pb-12 md:pt-8"><div className="mx-auto max-w-[1000px]">
    <header className="flex items-center gap-3"><Link href="/app" aria-label="Quay lại tổng quan" className="flex h-10 w-10 items-center justify-center rounded-full border border-[var(--border)] bg-[var(--surface)]"><ChevronLeft size={19} /></Link><div><p className="text-sm text-[var(--muted)]">Hiểu dòng tiền của bạn</p><h1 className="mt-1 text-2xl font-bold tracking-tight md:text-3xl">Báo cáo</h1></div></header>
    {!configured && <div className="mt-5 rounded-2xl border border-dashed border-[var(--border)] bg-[var(--surface-muted)] px-4 py-3 text-sm text-[var(--muted)]">Bản xem trước · số liệu dưới đây là dữ liệu minh họa, chưa được lưu.</div>}
    <div className="mt-6 flex flex-wrap items-center gap-2 rounded-2xl bg-[var(--surface)] p-1.5 shadow-sm">{Object.entries(rangeLabels).map(([value, label]) => <button type="button" key={value} onClick={() => changeRange(value)} className={`min-h-10 rounded-xl px-3 text-sm font-semibold ${report.range === value ? "bg-[var(--brand)] text-white" : "text-[var(--muted)] hover:bg-[var(--surface-muted)]"}`}>{label}</button>)}</div>
    {report.range === "custom" && <div className="mt-3 flex flex-wrap items-end gap-3 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-4"><label className="text-sm font-semibold">Từ ngày<input type="date" defaultValue={report.from} onChange={(event) => router.push(`/app/reports?range=custom&from=${event.target.value}&to=${report.to}`)} className="mt-1 min-h-10 rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 font-normal" /></label><span className="pb-2 text-[var(--muted)]">đến</span><label className="text-sm font-semibold">Ngày kết thúc<input type="date" defaultValue={report.to} onChange={(event) => router.push(`/app/reports?range=custom&from=${report.from}&to=${event.target.value}`)} className="mt-1 min-h-10 rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 font-normal" /></label></div>}
    <div className="mt-7 flex items-center justify-between gap-4"><div><p className="text-sm text-[var(--muted)]">Kỳ báo cáo</p><h2 className="mt-1 text-xl font-bold">{report.periodLabel}</h2></div><span className="flex items-center gap-1.5 text-sm text-[var(--muted)]"><CalendarDays size={16} /> {report.transactionCount} giao dịch</span></div>
    <section className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Card className="p-4"><div className="flex items-center justify-between"><p className="text-sm text-[var(--muted)]">Thu nhập</p><ArrowDownLeft size={18} className="text-[var(--brand)]" /></div><p className="mt-3 text-xl font-bold tabular-nums">{formatCurrency(report.income)}</p></Card><Card className="p-4"><div className="flex items-center justify-between"><p className="text-sm text-[var(--muted)]">Chi tiêu</p><ArrowUpRight size={18} className="text-[var(--warning)]" /></div><p className="mt-3 text-xl font-bold tabular-nums">{formatCurrency(report.expense)}</p></Card><Card className="p-4"><div className="flex items-center justify-between"><p className="text-sm text-[var(--muted)]">Dòng tiền ròng</p>{report.net >= 0 ? <TrendingUp size={18} className="text-[var(--brand)]" /> : <TrendingDown size={18} className="text-[var(--danger)]" />}</div><p className={`mt-3 text-xl font-bold tabular-nums ${report.net < 0 ? "text-[var(--danger)]" : ""}`}>{formatCurrency(report.net)}</p></Card><Card className="p-4"><div className="flex items-center justify-between"><p className="text-sm text-[var(--muted)]">Tỷ lệ tiết kiệm</p><BarChart3 size={18} className="text-[var(--brand)]" /></div><p className={`mt-3 text-xl font-bold tabular-nums ${report.savingRate < 0 ? "text-[var(--danger)]" : ""}`}>{report.savingRate.toFixed(1)}%</p></Card></section>
    <div className="mt-5 grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><Card><CardHeader><CardTitle>Thu và chi theo thời gian</CardTitle><p className="mt-1 text-xs text-[var(--muted)]">{report.trendLabel}</p></CardHeader><CardContent className="pt-2"><ReportChart data={report.trend} /></CardContent></Card><Card><CardHeader><CardTitle>Nhóm chi tiêu nổi bật</CardTitle><p className="mt-1 text-xs text-[var(--muted)]">Trong {report.periodLabel.toLowerCase()}</p></CardHeader><CardContent className="space-y-4 pt-2">{report.topCategories.length > 0 ? report.topCategories.map((category) => <div key={category.id}><div className="flex items-center justify-between gap-3 text-sm"><span className="flex min-w-0 items-center gap-2"><span className="h-2.5 w-2.5 shrink-0 rounded-full" style={{ background: category.color }} /><span className="truncate">{category.name}</span></span><span className="shrink-0 font-semibold tabular-nums">{formatCurrency(category.amount)}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-[var(--surface-muted)]"><div className="h-full rounded-full" style={{ width: `${category.percentage}%`, background: category.color }} /></div><p className="mt-1 text-right text-xs text-[var(--muted)]">{category.percentage.toFixed(1)}%</p></div>) : <p className="py-8 text-center text-sm text-[var(--muted)]">Chưa có khoản chi trong kỳ này.</p>}</CardContent></Card></div>
  </div></main>;
}
