"use client";

import Link from "next/link";
import { ArrowDownLeft, ArrowUpRight, Bell, ChevronRight, Coffee, MoreHorizontal, PiggyBank, Plus, ShoppingBag, Sparkles, WalletCards } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { BottomNav } from "@/components/layout/bottom-nav";
import { formatCurrency } from "@/lib/utils";

const spending = [
  { label: "Ăn uống", amount: 2180000, color: "#087f5b" },
  { label: "Di chuyển", amount: 820000, color: "#efaa47" },
  { label: "Mua sắm", amount: 320000, color: "#8795c4" },
];

const transactions = [
  { name: "Highlands Coffee", category: "Ăn uống · Hôm nay, 09:42", amount: -65000, icon: Coffee, tint: "#fff1dc" },
  { name: "Lương tháng 9", category: "Thu nhập · Hôm qua, 08:00", amount: 18000000, icon: WalletCards, tint: "#dff4e9" },
  { name: "Siêu thị WinMart", category: "Mua sắm · 05/09/2026", amount: -485000, icon: ShoppingBag, tint: "#e8edff" },
];

function Money({ amount }: { amount: number }) { return <span className="tabular-nums">{formatCurrency(Math.abs(amount))}</span>; }

export function DashboardView({ preview = false }: { preview?: boolean }) {
  const href = (path: string) => (preview ? "#" : path);
  return <div className="app-shell bg-[var(--background)]"><div className="desktop-grid mx-auto grid max-w-[1440px]">
    <aside className="hidden min-h-screen border-r border-[var(--border)] bg-[var(--surface)] p-7 md:block"><div className="mb-12 flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-[14px] bg-[var(--brand)] text-white"><PiggyBank size={21} /></div><span className="text-xl font-bold tracking-tight">monee</span></div><p className="mb-3 px-3 text-xs font-semibold uppercase tracking-[.16em] text-[var(--muted)]">Không gian của bạn</p><nav className="space-y-1" aria-label="Điều hướng desktop">{[["Tổng quan", "/app"], ["Tài khoản", "/app/accounts"], ["Giao dịch", "/app/transactions"], ["Ngân sách", "/app/budgets"], ["Mục tiêu", "/app/goals"], ["Báo cáo", "/app/reports"]].map(([label, path], i) => <Link key={path} href={href(path)} className={`flex min-h-11 items-center rounded-xl px-3 text-sm font-semibold ${i === 0 ? "bg-[var(--brand-soft)] text-[var(--brand-strong)]" : "text-[var(--muted)] hover:bg-[var(--surface-muted)]"}`}>{label}</Link>)}</nav><div className="mt-auto pt-56"><div className="rounded-2xl bg-[var(--surface-muted)] p-4"><Sparkles size={19} className="mb-3 text-[var(--brand)]" /><p className="text-sm font-semibold">Monee đang cùng bạn</p><p className="mt-1 text-xs leading-5 text-[var(--muted)]">Ghi lại từng khoản nhỏ để hiểu hơn về thói quen của mình.</p></div></div></aside>
    <main className="min-w-0 px-4 pb-28 pt-5 sm:px-6 md:px-10 md:pb-12 md:pt-8 lg:px-14"><header className="mx-auto flex max-w-[1060px] items-center justify-between"><div><p className="text-sm text-[var(--muted)]">Thứ Hai, 07 tháng 9</p><h1 className="mt-1 text-2xl font-bold tracking-tight md:text-3xl">Chào buổi sáng, Kien <span aria-hidden="true">👋</span></h1></div><button aria-label="Xem thông báo" className="relative flex h-11 w-11 items-center justify-center rounded-full border border-[var(--border)] bg-[var(--surface)] text-[var(--foreground)]"><Bell size={19} /><span className="absolute right-2.5 top-2 h-2 w-2 rounded-full bg-[#eb7665]" /></button></header>
      <div className="mx-auto mt-7 max-w-[1060px] space-y-5"><section className="overflow-hidden rounded-[24px] bg-[var(--brand)] p-6 text-white surface-shadow md:p-8"><div className="flex items-start justify-between"><div><p className="text-sm text-white/75">Tổng tài sản</p><p className="mt-2 text-3xl font-bold tracking-tight tabular-nums md:text-4xl">35.850.000 ₫</p></div><span className="rounded-full bg-white/15 px-3 py-1.5 text-xs font-semibold">Tháng 9 <ChevronRight size={13} className="ml-1 inline" /></span></div><div className="mt-8 grid grid-cols-2 gap-5 border-t border-white/15 pt-4"><div><p className="text-xs text-white/65">Thu nhập tháng này</p><p className="mt-1 font-semibold tabular-nums">+18.000.000 ₫</p></div><div><p className="text-xs text-white/65">Chi tiêu tháng này</p><p className="mt-1 font-semibold tabular-nums">−3.320.000 ₫</p></div></div></section>
        <section className="grid grid-cols-2 gap-3 md:grid-cols-4"><Card className="p-4"><div className="mb-4 flex h-9 w-9 items-center justify-center rounded-xl bg-[#dff4e9] text-[var(--brand)]"><ArrowDownLeft size={18} /></div><p className="text-xs text-[var(--muted)]">Dòng tiền ròng</p><p className="mt-1 text-lg font-bold tabular-nums">+14.680.000 ₫</p></Card><Card className="p-4"><div className="mb-4 flex h-9 w-9 items-center justify-center rounded-xl bg-[#fff0de] text-[#c88029]"><ArrowUpRight size={18} /></div><p className="text-xs text-[var(--muted)]">Tỷ lệ tiết kiệm</p><p className="mt-1 text-lg font-bold tabular-nums">81,6%</p></Card><Card className="col-span-2 p-4 md:col-span-2"><div className="flex items-center justify-between"><div><p className="text-xs text-[var(--muted)]">Ngân sách tháng</p><p className="mt-1 text-lg font-bold tabular-nums">3.320.000 <span className="text-sm font-medium text-[var(--muted)]">/ 5.000.000 ₫</span></p></div><span className="text-sm font-bold text-[var(--brand)]">66%</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-[var(--surface-muted)]"><div className="h-full w-[66%] rounded-full bg-[var(--brand)]" /></div><p className="mt-2 text-xs text-[var(--muted)]">Còn lại 1.680.000 ₫ cho 23 ngày</p></Card></section>
        <div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><Card><CardHeader><div className="flex items-center justify-between"><CardTitle>Chi tiêu theo nhóm</CardTitle><button aria-label="Xem thêm thống kê" className="rounded-lg p-2 text-[var(--muted)] hover:bg-[var(--surface-muted)]"><MoreHorizontal size={19} /></button></div></CardHeader><CardContent><div className="flex items-center gap-6"><div className="relative h-36 w-36 shrink-0 rounded-full" style={{ background: "conic-gradient(#087f5b 0 68%, #efaa47 68% 90%, #8795c4 90% 100%)" }}><div className="absolute inset-5 flex flex-col items-center justify-center rounded-full bg-[var(--surface)]"><span className="text-xl font-bold tabular-nums">3,3tr</span><span className="text-[11px] text-[var(--muted)]">tổng chi</span></div></div><div className="min-w-0 flex-1 space-y-3">{spending.map((item) => <div key={item.label} className="flex items-center justify-between gap-3 text-sm"><span className="flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full" style={{ background: item.color }} />{item.label}</span><span className="font-semibold tabular-nums">{formatCurrency(item.amount).replace(" ₫", "")}</span></div>)}</div></div></CardContent></Card>
          <Card><CardHeader><div className="flex items-center justify-between"><CardTitle>Mục tiêu của bạn</CardTitle><Link href={href("/app/goals")} className="text-xs font-semibold text-[var(--brand)]">Xem tất cả</Link></div></CardHeader><CardContent><div className="flex items-center gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#e8edff] text-xl">🏖️</div><div className="min-w-0 flex-1"><div className="flex justify-between text-sm"><span className="font-semibold">Du lịch Đà Nẵng</span><span className="font-bold text-[var(--brand)]">42%</span></div><div className="mt-2 h-2 rounded-full bg-[var(--surface-muted)]"><div className="h-full w-[42%] rounded-full bg-[#8795c4]" /></div><p className="mt-2 text-xs text-[var(--muted)] tabular-nums">8.400.000 / 20.000.000 ₫</p></div></div><button className="mt-5 flex min-h-11 w-full items-center justify-center gap-2 rounded-xl border border-dashed border-[var(--border)] text-sm font-semibold text-[var(--brand)] hover:bg-[var(--surface-muted)]"><Plus size={16} /> Thêm khoản tiết kiệm</button></CardContent></Card></div>
        <Card><CardHeader><div className="flex items-center justify-between"><CardTitle>Giao dịch gần đây</CardTitle><Link href={href("/app/transactions")} className="text-xs font-semibold text-[var(--brand)]">Xem tất cả <ChevronRight size={13} className="inline" /></Link></div></CardHeader><CardContent className="space-y-1 pt-2">{transactions.map((item) => { const Icon = item.icon; return <div key={item.name} className="flex items-center gap-3 rounded-xl py-3"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl" style={{ background: item.tint }}><Icon size={19} className="text-[var(--foreground)]" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{item.name}</p><p className="mt-0.5 text-xs text-[var(--muted)]">{item.category}</p></div><p className={`text-sm font-bold tabular-nums ${item.amount > 0 ? "text-[var(--brand)]" : "text-[var(--foreground)]"}`}>{item.amount > 0 ? "+" : "−"}<Money amount={item.amount} /></p></div> })}</CardContent></Card>
      </div></main></div><BottomNav preview={preview} />{preview && <div className="fixed bottom-20 left-1/2 z-10 -translate-x-1/2 rounded-full border border-[var(--border)] bg-[var(--surface)] px-3 py-1.5 text-xs font-medium text-[var(--muted)] shadow-md md:bottom-5">Bản xem trước · dữ liệu mẫu</div>}</div>;
}
