"use client";

import { useTransition } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Bell, Check, ChevronLeft, CircleAlert, Repeat2, Target } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { markNotificationReadAction } from "@/features/notifications/actions/update-notifications";
import type { NotificationRecord } from "@/features/notifications/queries/get-notifications";

const demoNotifications: NotificationRecord[] = [{ id: "demo-notification", type: "budget_warning", title: "Ngân sách sắp chạm giới hạn", message: "Chi tiêu Ăn uống đã đạt 78% ngân sách tháng này.", is_read: false, created_at: "2026-09-09T08:00:00+07:00" }];
function dateLabel(value: string) { return new Intl.DateTimeFormat("vi-VN", { day: "2-digit", month: "2-digit", hour: "2-digit", minute: "2-digit", timeZone: "Asia/Ho_Chi_Minh" }).format(new Date(value)); }
function iconFor(type: NotificationRecord["type"]) { return type === "recurring_transaction" ? Repeat2 : type === "saving_goal" ? Target : type === "budget_warning" || type === "budget_exceeded" ? CircleAlert : Bell; }

export function NotificationsView({ notifications, configured }: { notifications: NotificationRecord[]; configured: boolean }) {
  const router = useRouter(); const [isPending, startTransition] = useTransition(); const visible = configured ? notifications : demoNotifications; const unread = visible.filter((item) => !item.is_read).length;
  function markRead(id: string | null) { if (!configured) return; startTransition(async () => { const result = await markNotificationReadAction(id); if (!result.ok) { toast.error(result.error); return; } toast.success(id ? "Đã đánh dấu thông báo đã đọc." : "Đã đánh dấu tất cả thông báo đã đọc."); router.refresh(); }); }
  return <main className="min-h-screen bg-[var(--background)] px-4 pb-28 pt-5 sm:px-6 md:px-10 md:pb-12 md:pt-8"><div className="mx-auto max-w-[760px]"><header className="flex items-center justify-between gap-4"><div className="flex items-center gap-3"><Link href="/app" aria-label="Quay lại tổng quan" className="flex h-10 w-10 items-center justify-center rounded-full border border-[var(--border)] bg-[var(--surface)]"><ChevronLeft size={19} /></Link><div><p className="text-sm text-[var(--muted)]">Cập nhật dành cho bạn</p><h1 className="mt-1 text-2xl font-bold tracking-tight md:text-3xl">Thông báo</h1></div></div>{configured && unread > 0 && <Button variant="outline" size="sm" onClick={() => markRead(null)} disabled={isPending}><Check size={15} /> Đọc tất cả</Button>}</header>{!configured && <div className="mt-5 rounded-2xl border border-dashed border-[var(--border)] bg-[var(--surface-muted)] px-4 py-3 text-sm text-[var(--muted)]">Bản xem trước · thông báo dưới đây là dữ liệu minh họa.</div>}<section className="mt-6 space-y-2">{visible.length === 0 ? <Card><CardContent className="p-10 text-center"><Bell className="mx-auto text-[var(--brand)]" size={30} /><p className="mt-3 font-semibold">Chưa có thông báo</p><p className="mt-1 text-sm text-[var(--muted)]">Monee sẽ hiển thị các cập nhật quan trọng tại đây.</p></CardContent></Card> : visible.map((notification) => { const Icon = iconFor(notification.type); return <Card key={notification.id} className={`p-4 ${notification.is_read ? "opacity-70" : "border-[var(--brand)]"}`}><div className="flex items-start gap-3"><div className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${notification.is_read ? "bg-[var(--surface-muted)] text-[var(--muted)]" : "bg-[var(--brand-soft)] text-[var(--brand)]"}`}><Icon size={18} /></div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{notification.title}</p><p className="mt-1 text-sm leading-6 text-[var(--muted)]">{notification.message}</p></div>{!notification.is_read && <span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-[var(--brand)]" />}</div><div className="mt-3 flex items-center justify-between gap-3 text-xs text-[var(--muted)]"><span>{dateLabel(notification.created_at)}</span>{!notification.is_read && configured && <button type="button" onClick={() => markRead(notification.id)} className="font-semibold text-[var(--brand)]">Đánh dấu đã đọc</button>}</div></div></div></Card>; })}</section></div></main>;
}
